[package]
name = "reth-optimism-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A payload builder for op-reth that builds optimistic payloads."

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-revm.workspace = true
reth-transaction-pool.workspace = true
reth-provider.workspace = true
reth-payload-builder.workspace = true
reth-basic-payload-builder.workspace = true

# ethereum
revm.workspace = true

# misc
tracing.workspace = true
thiserror.workspace = true


[features]
# This is a workaround for reth-cli crate to allow this as mandatory dependency without breaking the build even if unused.
# This makes managing features and testing workspace easier because clippy always builds all members if --workspace is provided
optimism = [
    "reth-primitives/optimism",
    "reth-revm/optimism",
    "reth-transaction-pool/optimism",
    "reth-provider/optimism",
    "reth-payload-builder/optimism",
]
telos = [
    "revm/telos",
]
