[package]
name = "reth-interfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-primitives.workspace = true
reth-nippy-jar.workspace = true
reth-rpc-types.workspace = true
reth-network-api.workspace = true
# TODO(onbjerg): We only need this for [BlockBody]
reth-eth-wire.workspace = true

# async
futures.workspace = true
tokio = { workspace = true, features = ["sync"] }

# misc
auto_impl = "1.0"
thiserror.workspace = true
tracing.workspace = true
secp256k1 = { workspace = true, default-features = false, features = [
    "alloc",
    "recovery",
    "rand",
], optional = true }
clap = { workspace = true, features = ["derive"], optional = true }
parking_lot = { workspace = true, optional = true }
rand = { workspace = true, optional = true }

# telos
reth-telos = { workspace = true, optional = true }

[dev-dependencies]
parking_lot.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full"] }
secp256k1 = { workspace = true, features = ["alloc", "recovery", "rand"] }

[features]
test-utils = ["secp256k1", "rand", "parking_lot"]
cli = ["clap"]
optimism = ["reth-eth-wire/optimism"]
telos = ["dep:reth-telos"]
