[package]
name = "reth-trie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Merkle trie implementation"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-db.workspace = true
revm.workspace = true

# alloy
alloy-rlp.workspace = true
alloy-chains.workspace = true

# tracing
tracing.workspace = true

# misc
thiserror.workspace = true
derive_more = "0.99"
auto_impl = "1"

# test-utils
triehash = { version = "0.8", optional = true }

[dev-dependencies]
# reth
reth-primitives = { workspace = true, features = ["test-utils", "arbitrary"] }
reth-db = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }

# trie
triehash = "0.8"

# misc
proptest.workspace = true
tokio = { workspace = true, default-features = false, features = ["sync", "rt", "macros"] }
tokio-stream.workspace = true
once_cell.workspace = true
serde_json.workspace = true
similar-asserts.workspace = true
criterion.workspace = true

[features]
test-utils = ["triehash"]
telos = [
    "revm/telos",
]

[[bench]]
name = "prefix_set"
harness = false
